import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`w-full min-h-screen bg-gradient-to-t from-slate-950 to-neutral-950 text-slate-200 ${inter.className}`}>
        <Header />
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}
